# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/welcome.ipynb

<p><img alt="Colaboratory logo" height="45px" src="https://colab.research.google.com/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>Welcome to Colaboratory!</h1>


Colaboratory is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

With Colaboratory you can write and execute code, save and share your analyses, and access powerful computing resources, all for free from your browser.
"""

import numpy as np
print("Enter the value of M")
m=int(input())
print("Enter the value of N")
n=int(input())
print("Enter Array Elements")
x = [x for x in input()]
a = np.array(x)
b=len(a)
print(b)
if b==m*n:
  print(a.reshape(m, n))
else :
  print("EITHER TOO LESS OR TOO MANY ELEMENTS")
