# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-btSsrIXrpm_BkKp3ltdTq6RjXob8gAa
"""

import numpy as np
import random
file=open('file','a')
z = np.array([[0, 0, 0], [0, 0, 0],[0,0,0]]);
i=0
win=0
value = 0
while(i<5):
  value=0
  while(value==0):
    x= input("enter the x cordinate(1-3):")
    y= input("enter the y cordinate(1-3):")
    valx=int(x)-1
    valy=int(y)-1
    if(z[valx,valy]==0):
      z[valx,valy]=1
      i=i+1;
      value=1
    else:
      print("WRONG ENTRY")
  value=0
  while(value==0 and i<5):
    compvalx=random.randint(0,2)
    compvaly=random.randint(0,2)
    if(z[compvalx,compvaly]==0):
        value=1
  z[compvalx,compvaly]=2
  for j in range(0,3):
    if(z[j][0]==1 and z[j][1]==1 and z[j][2]==1):
      print("YOU WIN")
      file.write("you won\n")
      win=1
    elif(z[0][j]==1 and z[1][j]==1 and z[2][j]==1):
      print("YOU WIN")
      file.write("you won\n")
      win=1
  for p in range(0,3):
    for q in range (0,3):
      if(z[p,q]==1):
        print("X ",end='')
      elif(z[p,q]==2):
        print("O ",end='')
      else:
        print("- ",end='')
    print("\n")
  if(z[0][0]==1 and z[1][1]==1 and z[2][2]==1):
    print("YOU WIN")
    file.write("you won\n")
    win=1
  elif(z[0][2]==1 and z[1][1]==1 and z[2][0]==1):
    print("YOU WIN")
    file.write("you won\n")
    win=1
  for j in range(0,3):
    if(z[j][0]==2 and z[j][1]==2 and z[j][2]==2):
      print("YOU LOSE")
      file.write("you lose\n")
      win=1
    elif(z[0][j]==2 and z[1][j]==2 and z[2][j]==2):
      print("YOU LOSE")
      file.write("you lose\n")
      win=1
    
  if(z[0][0]==2 and z[1][1]==2 and z[2][2]==2):
    print("YOU LOSE")
    file.write("you lose\n")
    win=1
  elif(z[0][2]==2 and z[1][1]==2 and z[2][0]==2):
    print("YOU LOSE")
    file.write("you lose\n")
    win=1
  if(win==1):
    break
if(win==0):
  print("GAME TIED")
  file.write("you drew\n")



